### PR TITLE
Update `mod_tile` to latest commit from `2023.07.20` (EL9)

### PR DESCRIPTION
**Pull request by hummeltech**
**Also:**
* Move user & group creation into `sysusers.d`
  * Not yet integrated into EL9's RPM `v4.16` (see [here](https://rpm-software-management.github.io/rpm/manual/users_and_groups.html))
    * So explicitly run `systemd-sysusers` on `%post`
* Move `%{renderd_home}` directory creation into `tmpfiles.d`
  * As per `sysusers.d` man page recommendation
  * Explicitly run `systemd-tmpfiles` on `%post`
* No longer create `/etc/httpd/conf.modules.d/11-tile.conf` & `/etc/renderd.conf` files
  * Now generated during `cmake --install`
* Change `ModTileRenderdSocketAddr` to `ModTileRenderdSocketName` in example Apache config
  * Since the provided `/etc/renderd.conf` now also uses this

### CODE REVIEW

**Comment by jbronn** [comment]
I'm +1 on the upgrade, but -1 on adding a dependency to SystemD, it's something that's not installed by default in container images.

**Comment by hummeltech** [comment]
Oh, that's no fun, everything it needed was installed in the `rpmbuild-generic` image, so I mistakenly assumed it would be available.

**Comment by hummeltech** [comment]
I can probably just add back the `%pre` and the directory creation and remove the calls to those two `systemd-*` executables.

**Review by jbronn — APPROVED** [review]
LGTM, I added some minor changes in befd4af.

While the `rpmbuild-generic` container has `systemd-libs` installed it actually doesn't have the the `/usr/bin/systemd-{sysusers,tmpfiles}` executables and neither do the `centos:7`/`quay.io/centos/centos:stream9` base images.  For RPMs with SystemD units we'll add `systemd-rpm-macros` as a `BuildRequires` so that we can use the `%systemd_{post,preun,postun}` macros for registering/uninstalling those units.

Unfortunately, we still have to create users/run directories in the RPM so that containers without SystemD (the majority of them) "just work."

**Comment by hummeltech** [comment]
Yes, I see now that you are correct, I used `rpmbuild-generic` in order to test out the RPM installation and it only worked because `systemd` is installed as a dependency of `mod_tile` which led me to believe it was already installed:
```shell
$ COMPOSE_FILE=docker-compose.el9.yml docker-compose run --rm --user=root rpmbuild-generic yum -y install /rpmbuild/RPMS/x86_64/mod_tile-0.6.1-5.el9.x86_64.rpm
...
Dependencies resolved.
===============================================================================================================================================================================================================================================================================
 Package                                                                     Architecture                                           Version                                                           Repository                                                          Size
===============================================================================================================================================================================================================================================================================
Installing:
 mod_tile                                                                    x86_64                                                 0.6.1-5.el9                                                       @commandline                                                       355 k
Installing dependencies:
...
 systemd                                                                     x86_64                                                 252-15.el9                                                        baseos                                                             4.1 M
 systemd-pam                                                                 x86_64                                                 252-15.el9                                                        baseos                                                             255 k
 systemd-rpm-macros                                                          noarch                                                 252-15.el9                                                        baseos                                                              44 k
...
```

**Comment by jbronn** [comment]
Fired up a clean `quay.io/centos/centos:stream9` image and installed `httpd`; that's where the `systemd` requirement is coming from, even in containers.

As such, `/usr/bin/systemd-{sysusers,tempfiles}` are available for use -- if you want to revert back to using them, I'm fine with that.  Apologies for the confusion, didn't know that `systemd` had been riding along fine with any EL9 container with Apache installed.

**Comment by hummeltech** [comment]
Sure thing, I think it's a little bit cleaner like this. Thanks!

**Comment by jbronn** [comment]
Signed & published.

**Pull request merged**
